import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        'apple-blue': 'var(--apple-blue)',
        'apple-blue-dark': 'var(--apple-blue-dark)',
        // VG Educational Color System
        'vg-primary': {
          50: 'var(--vg-primary-50)',
          100: 'var(--vg-primary-100)',
          200: 'var(--vg-primary-200)',
          300: 'var(--vg-primary-300)',
          400: 'var(--vg-primary-400)',
          500: 'var(--vg-primary-500)',
          600: 'var(--vg-primary-600)',
          700: 'var(--vg-primary-700)',
          800: 'var(--vg-primary-800)',
          900: 'var(--vg-primary-900)',
        },
        'vg-sanskrit': {
          50: 'var(--vg-sanskrit-50)',
          100: 'var(--vg-sanskrit-100)',
          200: 'var(--vg-sanskrit-200)',
          300: 'var(--vg-sanskrit-300)',
          400: 'var(--vg-sanskrit-400)',
          500: 'var(--vg-sanskrit-500)',
          600: 'var(--vg-sanskrit-600)',
          700: 'var(--vg-sanskrit-700)',
          800: 'var(--vg-sanskrit-800)',
          900: 'var(--vg-sanskrit-900)',
        },
        'vg-cultural': {
          50: 'var(--vg-cultural-50)',
          100: 'var(--vg-cultural-100)',
          200: 'var(--vg-cultural-200)',
          300: 'var(--vg-cultural-300)',
          400: 'var(--vg-cultural-400)',
          500: 'var(--vg-cultural-500)',
          600: 'var(--vg-cultural-600)',
          700: 'var(--vg-cultural-700)',
          800: 'var(--vg-cultural-800)',
          900: 'var(--vg-cultural-900)',
        },
        'vg-success': {
          50: 'var(--vg-success-50)',
          100: 'var(--vg-success-100)',
          500: 'var(--vg-success-500)',
          600: 'var(--vg-success-600)',
          700: 'var(--vg-success-700)',
        },
        'vg-warning': {
          50: 'var(--vg-warning-50)',
          100: 'var(--vg-warning-100)',
          500: 'var(--vg-warning-500)',
          600: 'var(--vg-warning-600)',
          700: 'var(--vg-warning-700)',
        },
        'vg-error': {
          50: 'var(--vg-error-50)',
          100: 'var(--vg-error-100)',
          500: 'var(--vg-error-500)',
          600: 'var(--vg-error-600)',
          700: 'var(--vg-error-700)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sf-pro)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'monospace'],
        'vg-primary': ['var(--font-vg-primary)', 'system-ui', 'sans-serif'],
        'vg-cultural': ['var(--font-vg-cultural)', 'serif'],
      },
      fontSize: {
        'vg-xs': 'var(--font-size-vg-xs)',
        'vg-sm': 'var(--font-size-vg-sm)',
        'vg-base': 'var(--font-size-vg-base)',
        'vg-lg': 'var(--font-size-vg-lg)',
        'vg-xl': 'var(--font-size-vg-xl)',
        'vg-2xl': 'var(--font-size-vg-2xl)',
        'vg-3xl': 'var(--font-size-vg-3xl)',
        'vg-4xl': 'var(--font-size-vg-4xl)',
        'vg-5xl': 'var(--font-size-vg-5xl)',
      },
      spacing: {
        'vg-0': 'var(--spacing-vg-0)',
        'vg-1': 'var(--spacing-vg-1)',
        'vg-2': 'var(--spacing-vg-2)',
        'vg-3': 'var(--spacing-vg-3)',
        'vg-4': 'var(--spacing-vg-4)',
        'vg-5': 'var(--spacing-vg-5)',
        'vg-6': 'var(--spacing-vg-6)',
        'vg-8': 'var(--spacing-vg-8)',
        'vg-10': 'var(--spacing-vg-10)',
        'vg-12': 'var(--spacing-vg-12)',
        'vg-16': 'var(--spacing-vg-16)',
        'vg-20': 'var(--spacing-vg-20)',
      },
      boxShadow: {
        'vg-xs': 'var(--box-shadow-vg-xs)',
        'vg-sm': 'var(--box-shadow-vg-sm)',
        'vg-md': 'var(--box-shadow-vg-md)',
        'vg-lg': 'var(--box-shadow-vg-lg)',
        'vg-xl': 'var(--box-shadow-vg-xl)',
        'vg-2xl': 'var(--box-shadow-vg-2xl)',
      },
      borderRadius: {
        'vg-sm': 'var(--border-radius-vg-sm)',
        'vg-md': 'var(--border-radius-vg-md)',
        'vg-lg': 'var(--border-radius-vg-lg)',
        'vg-xl': 'var(--border-radius-vg-xl)',
        'vg-2xl': 'var(--border-radius-vg-2xl)',
        'vg-3xl': 'var(--border-radius-vg-3xl)',
      },
      animation: {
        'fade-in': 'var(--animation-vg-fade-in)',
        'scale-in': 'var(--animation-vg-scale-in)',
        'slide-in-right': 'var(--animation-vg-slide-in-right)',
        'slide-in-left': 'var(--animation-vg-slide-in-left)',
        'educational-pulse': 'var(--animation-vg-educational-pulse)',
        'cultural-glow': 'var(--animation-vg-cultural-glow)',
        'float': 'var(--animation-vg-float)',
      },
      backdropBlur: {
        'vg-sm': 'var(--backdrop-blur-vg-sm)',
        'vg-md': 'var(--backdrop-blur-vg-md)',
        'vg-lg': 'var(--backdrop-blur-vg-lg)',
        'vg-xl': 'var(--backdrop-blur-vg-xl)',
      },
      keyframes: {
        'vg-fade-in': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'vg-scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'vg-slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'vg-slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'vg-educational-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
        'vg-cultural-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(139, 92, 246, 0.3)' },
          '50%': { boxShadow: '0 0 30px rgba(139, 92, 246, 0.5)' },
        },
        'vg-float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}

export default config
