import { mysqlTable, mysqlSchema, AnyMySqlColumn, index, foreignKey, primaryKey, varchar, text, timestamp, json, int, unique, serial, bigint, decimal, mysqlEnum, date } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const account = mysqlTable("account", {
	id: varchar({ length: 255 }).notNull(),
	accountId: text("account_id").notNull(),
	providerId: text("provider_id").notNull(),
	userId: varchar("user_id", { length: 255 }).notNull().references(() => user.id, { onDelete: "cascade" } ),
	accessToken: text("access_token"),
	refreshToken: text("refresh_token"),
	idToken: text("id_token"),
	accessTokenExpiresAt: timestamp("access_token_expires_at", { mode: 'string' }),
	refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { mode: 'string' }),
	scope: text(),
	password: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow().notNull(),
},
(table) => [
	index("account_userId_idx").on(table.userId),
	primaryKey({ columns: [table.id], name: "account_id"}),
]);

export const adminActivityLog = mysqlTable("admin_activity_log", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	adminId: text("admin_id"),
	action: text(),
	details: json(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "admin_activity_log_id"}),
]);

export const aiTutorUsage = mysqlTable("ai_tutor_usage", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	date: timestamp({ mode: 'string' }).default(sql`(now())`),
	questionsAsked: int("questions_asked").default(0),
	totalTokensUsed: int("total_tokens_used").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "ai_tutor_usage_id"}),
]);

export const answerFeedback = mysqlTable("answer_feedback", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	userId: varchar("user_id", { length: 255 }),
	questionText: text("question_text"),
	answerText: text("answer_text"),
	subject: varchar({ length: 100 }),
	classLevel: int("class_level"),
	board: varchar({ length: 50 }),
	starRating: int("star_rating"),
	thumbsRating: varchar("thumbs_rating", { length: 10 }),
	feedbackText: text("feedback_text"),
	validationStatus: varchar("validation_status", { length: 20 }).default('pending'),
	validatedBy: varchar("validated_by", { length: 255 }),
	validatedAt: timestamp("validated_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "answer_feedback_id"}),
	unique("id").on(table.id),
]);

export const classes = mysqlTable("classes", {
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	gradeLevel: int("grade_level").notNull(),
	qdrantNamespace: varchar("qdrant_namespace", { length: 255 }),
	subjects: json(),
	teacherIds: json("teacher_ids"),
	studentCount: int("student_count").default(0),
	settings: json(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "classes_id"}),
]);

export const communityPhrases = mysqlTable("community_phrases", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	wordId: bigint("word_id", { mode: "number", unsigned: true }).notNull().references(() => dictionaryWords.id),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkUserId: varchar("clerk_user_id", { length: 255 }),
	phrase: text().notNull(),
	context: text(),
	region: varchar({ length: 100 }),
	languageVariant: varchar("language_variant", { length: 50 }),
	isApproved: tinyint("is_approved").default(0),
	approvedBy: varchar("approved_by", { length: 255 }),
	approvedAt: timestamp("approved_at", { mode: 'string' }),
	rejectionReason: text("rejection_reason"),
	upvotes: int().default(0),
	downvotes: int().default(0),
	reports: int().default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "community_phrases_id"}),
	unique("id").on(table.id),
]);

export const dictionaryOfflineSync = mysqlTable("dictionary_offline_sync", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkUserId: varchar("clerk_user_id", { length: 255 }),
	syncVersion: int("sync_version").default(1),
	lastFullSync: timestamp("last_full_sync", { mode: 'string' }),
	lastIncrementalSync: timestamp("last_incremental_sync", { mode: 'string' }),
	wordsSynced: int("words_synced").default(0),
	audioFilesCached: int("audio_files_cached").default(0),
	totalCacheSizeMb: decimal("total_cache_size_mb", { precision: 8, scale: 2 }).default('0.00'),
	autoSyncEnabled: tinyint("auto_sync_enabled").default(1),
	wifiOnlySync: tinyint("wifi_only_sync").default(1),
	maxCacheSizeMb: int("max_cache_size_mb").default(100),
	pendingProgressUpdates: json("pending_progress_updates"),
	pendingPhraseSubmissions: json("pending_phrase_submissions"),
	pendingSearchHistory: json("pending_search_history"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "dictionary_offline_sync_id"}),
	unique("id").on(table.id),
	unique("dictionary_offline_sync_user_id_unique").on(table.userId),
]);

export const dictionarySearchHistory = mysqlTable("dictionary_search_history", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkUserId: varchar("clerk_user_id", { length: 255 }),
	searchQuery: varchar("search_query", { length: 255 }).notNull(),
	searchType: mysqlEnum("search_type", ['exact','fuzzy','phonetic','semantic']).notNull(),
	resultsCount: int("results_count").default(0),
	selectedWordId: bigint("selected_word_id", { mode: "number", unsigned: true }).references(() => dictionaryWords.id),
	searchContext: mysqlEnum("search_context", ['learning','quiz','browse','community']).default('browse'),
	deviceType: mysqlEnum("device_type", ['mobile','tablet','desktop']).default('desktop'),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "dictionary_search_history_id"}),
	unique("id").on(table.id),
]);

export const dictionaryUserStats = mysqlTable("dictionary_user_stats", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkUserId: varchar("clerk_user_id", { length: 255 }),
	totalWordsLearned: int("total_words_learned").default(0),
	wordsMastered: int("words_mastered").default(0),
	currentStreakDays: int("current_streak_days").default(0),
	longestStreakDays: int("longest_streak_days").default(0),
	// you can use { mode: 'date' }, if you want to have Date as type for this column
	lastActivityDate: date("last_activity_date", { mode: 'string' }),
	totalQuizAttempts: int("total_quiz_attempts").default(0),
	correctQuizAnswers: int("correct_quiz_answers").default(0),
	averageAccuracy: decimal("average_accuracy", { precision: 5, scale: 2 }).default('0.00'),
	totalPoints: int("total_points").default(0),
	level: int().default(1),
	badgesEarned: json("badges_earned"),
	achievements: json(),
	phrasesContributed: int("phrases_contributed").default(0),
	phrasesApproved: int("phrases_approved").default(0),
	communityReputation: int("community_reputation").default(0),
	dailyGoalWords: int("daily_goal_words").default(5),
	preferredDifficulty: mysqlEnum("preferred_difficulty", ['beginner','intermediate','advanced','mixed']).default('mixed'),
	notificationPreferences: json("notification_preferences"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "dictionary_user_stats_id"}),
	unique("id").on(table.id),
	unique("dictionary_user_stats_user_id_unique").on(table.userId),
	unique("dictionary_user_stats_clerk_user_id_unique").on(table.clerkUserId),
]);

export const dictionaryWords = mysqlTable("dictionary_words", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	word: varchar({ length: 255 }).notNull(),
	pronunciation: varchar({ length: 255 }),
	partOfSpeech: mysqlEnum("part_of_speech", ['noun','verb','adjective','adverb','pronoun','preposition','conjunction','interjection']).notNull(),
	englishDefinition: text("english_definition").notNull(),
	englishSynonyms: json("english_synonyms"),
	englishAntonyms: json("english_antonyms"),
	hindiTranslation: varchar("hindi_translation", { length: 500 }).notNull(),
	hindiSynonyms: json("hindi_synonyms"),
	devanagariScript: varchar("devanagari_script", { length: 500 }),
	amarkoshaCategory: varchar("amarkosha_category", { length: 100 }),
	semanticCluster: varchar("semantic_cluster", { length: 100 }),
	etymology: text(),
	examples: json(),
	culturalContext: text("cultural_context"),
	regionalUsage: json("regional_usage"),
	audioUrl: varchar("audio_url", { length: 500 }),
	audioAccent: mysqlEnum("audio_accent", ['indian','british','american']).default('indian'),
	difficultyLevel: mysqlEnum("difficulty_level", ['beginner','intermediate','advanced']).default('intermediate'),
	frequencyRank: int("frequency_rank"),
	source: varchar({ length: 100 }).default('system'),
	isActive: tinyint("is_active").default(1),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "dictionary_words_id"}),
	unique("id").on(table.id),
	unique("dictionary_words_word_unique").on(table.word),
]);

export const enhancedUserProfiles = mysqlTable("enhanced_user_profiles", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	userId: varchar("user_id", { length: 255 }),
	role: mysqlEnum(['student','teacher','parent','admin','parent_guardian']).default('student'),
	boardType: mysqlEnum("board_type", ['CBSE','ICSE','STATE_BOARD','ALL','State']).default('CBSE'),
	medium: mysqlEnum(['ENGLISH','HINDI']).default('ENGLISH'),
	gradeLevel: int("grade_level"),
	stream: mysqlEnum(['HUMANITIES','BIOLOGY','MATHEMATICS','COMMERCE']),
	subjects: json(),
	preferences: json(),
	learningStyle: varchar("learning_style", { length: 50 }).default('mixed'),
	learningPace: varchar("learning_pace", { length: 50 }).default('average'),
	preferredExplanationComplexity: varchar("preferred_explanation_complexity", { length: 50 }).default('intermediate'),
	languagePreference: varchar("language_preference", { length: 50 }).default('english'),
	teachingExperienceYears: int("teaching_experience_years"),
	specializationSubjects: json("specialization_subjects"),
	classroomSizePreference: int("classroom_size_preference"),
	childGradeLevels: json("child_grade_levels"),
	involvementLevel: varchar("involvement_level", { length: 50 }),
	supportPreferences: json("support_preferences"),
	interactionHistory: json("interaction_history"),
	performanceMetrics: json("performance_metrics"),
	difficultyPreferences: json("difficulty_preferences"),
	isOnboardingComplete: tinyint("is_onboarding_complete").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "enhanced_user_profiles_id"}),
	unique("id").on(table.id),
	unique("enhanced_user_profiles_user_id_unique").on(table.userId),
]);

export const freeTrials = mysqlTable("free_trials", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	trialStart: timestamp("trial_start", { mode: 'string' }).default(sql`(now())`),
	trialEnd: timestamp("trial_end", { mode: 'string' }),
	isConverted: tinyint("is_converted").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "free_trials_id"}),
]);

export const googleDriveConfig = mysqlTable("google_drive_config", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	accessToken: text("access_token"),
	refreshToken: text("refresh_token"),
	tokenType: text("token_type"),
	scope: text(),
	expiryDate: timestamp("expiry_date", { mode: 'string' }),
	configuredBy: text("configured_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "google_drive_config_id"}),
]);

export const googleDriveFolders = mysqlTable("google_drive_folders", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	folderId: varchar("folder_id", { length: 255 }).notNull(),
	folderName: varchar("folder_name", { length: 255 }).notNull(),
	parentFolderId: varchar("parent_folder_id", { length: 255 }),
	folderPath: text("folder_path").notNull(),
	board: mysqlEnum(['CBSE','ICSE','STATE_BOARD','ALL','State']),
	class: int(),
	subject: varchar({ length: 100 }),
	materialType: mysqlEnum("material_type", ['notes','summaries','mind_maps','quizzes','textbooks','reference']),
	isActive: tinyint("is_active").default(1),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "google_drive_folders_id"}),
	unique("google_drive_folders_folder_id_unique").on(table.folderId),
]);

export const institutionProfiles = mysqlTable("institution_profiles", {
	id: varchar({ length: 255 }).notNull(),
	organizationId: varchar("organization_id", { length: 255 }).notNull().references(() => organization.id, { onDelete: "cascade" } ),
	type: mysqlEnum(['school','college','tuition_center']).default('school').notNull(),
	address: text(),
	website: varchar({ length: 255 }),
	contactEmail: varchar("contact_email", { length: 255 }),
	contactPhone: varchar("contact_phone", { length: 50 }),
	establishedYear: int("established_year"),
	primaryColor: varchar("primary_color", { length: 50 }),
	logoUrl: text("logo_url"),
	bannerUrl: text("banner_url"),
	onboardingCompleted: tinyint("onboarding_completed").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "institution_profiles_id"}),
	unique("institution_profiles_organization_id_unique").on(table.organizationId),
]);

export const invitation = mysqlTable("invitation", {
	id: varchar({ length: 255 }).notNull(),
	organizationId: varchar("organization_id", { length: 255 }).notNull().references(() => organization.id, { onDelete: "cascade" } ),
	email: varchar({ length: 255 }).notNull(),
	role: varchar({ length: 255 }),
	status: varchar({ length: 255 }).default('pending').notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`).notNull(),
	inviterId: varchar("inviter_id", { length: 255 }).notNull().references(() => user.id, { onDelete: "cascade" } ),
},
(table) => [
	index("invitation_organizationId_idx").on(table.organizationId),
	index("invitation_email_idx").on(table.email),
	primaryKey({ columns: [table.id], name: "invitation_id"}),
]);

export const materialApprovalLog = mysqlTable("material_approval_log", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	materialId: varchar("material_id", { length: 36 }).references(() => materials.id),
	adminId: text("admin_id"),
	action: text(),
	comments: text(),
	ipAddress: text("ip_address"),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "material_approval_log_id"}),
]);

export const materials = mysqlTable("materials", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	title: varchar({ length: 255 }).notNull(),
	description: text(),
	type: mysqlEnum(['notes','summaries','mind_maps','quizzes','textbooks','reference']).notNull(),
	board: mysqlEnum(['CBSE','ICSE','STATE_BOARD','ALL','State']).notNull(),
	medium: mysqlEnum(['ENGLISH','HINDI']).notNull(),
	class: int().notNull(),
	stream: mysqlEnum(['HUMANITIES','BIOLOGY','MATHEMATICS','COMMERCE']),
	subject: varchar({ length: 100 }).notNull(),
	smType: varchar("sm_type", { length: 100 }).default('Chapter Notes'),
	googleDriveFileId: varchar("google_drive_file_id", { length: 255 }).notNull(),
	googleDriveFolderId: varchar("google_drive_folder_id", { length: 255 }),
	fileName: varchar("file_name", { length: 255 }).notNull(),
	fileSize: int("file_size").notNull(),
	mimeType: varchar("mime_type", { length: 100 }).default('application/pdf'),
	downloadUrl: text("download_url"),
	viewUrl: text("view_url"),
	thumbnailUrl: text("thumbnail_url"),
	downloadCount: int("download_count").default(0),
	viewCount: int("view_count").default(0),
	tags: json(),
	difficulty: varchar({ length: 50 }).default('medium'),
	metadata: json(),
	status: mysqlEnum(['draft','pending_review','approved','rejected','archived']).default('draft'),
	isActive: tinyint("is_active").default(1),
	createdBy: varchar("created_by", { length: 255 }),
	approvedBy: varchar("approved_by", { length: 255 }),
	rejectedBy: varchar("rejected_by", { length: 255 }),
	approvedAt: timestamp("approved_at", { mode: 'string' }),
	rejectedAt: timestamp("rejected_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "materials_id"}),
	unique("materials_google_drive_file_id_unique").on(table.googleDriveFileId),
]);

export const member = mysqlTable("member", {
	id: varchar({ length: 255 }).notNull(),
	organizationId: varchar("organization_id", { length: 255 }).notNull().references(() => organization.id, { onDelete: "cascade" } ),
	userId: varchar("user_id", { length: 255 }).notNull().references(() => user.id, { onDelete: "cascade" } ),
	role: varchar({ length: 255 }).default('member').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).notNull(),
},
(table) => [
	index("member_organizationId_idx").on(table.organizationId),
	index("member_userId_idx").on(table.userId),
	primaryKey({ columns: [table.id], name: "member_id"}),
]);

export const noteActivityLog = mysqlTable("note_activity_log", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	noteId: varchar("note_id", { length: 36 }).notNull().references(() => userNotes.id),
	userId: varchar("user_id", { length: 255 }).notNull(),
	activityType: mysqlEnum("activity_type", ['created','updated','viewed','shared','exported','deleted']).notNull(),
	changesSummary: text("changes_summary"),
	ipAddress: varchar("ip_address", { length: 45 }),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "note_activity_log_id"}),
	unique("id").on(table.id),
]);

export const noteFolders = mysqlTable("note_folders", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkId: varchar("clerk_id", { length: 255 }),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	color: varchar({ length: 20 }).default('blue'),
	icon: varchar({ length: 50 }).default('folder'),
	parentFolderId: varchar("parent_folder_id", { length: 36 }),
	folderPath: text("folder_path"),
	sortOrder: int("sort_order").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "note_folders_id"}),
]);

export const noteShares = mysqlTable("note_shares", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	noteId: varchar("note_id", { length: 36 }).notNull().references(() => userNotes.id),
	sharedByUserId: varchar("shared_by_user_id", { length: 255 }).notNull(),
	sharedWithUserId: varchar("shared_with_user_id", { length: 255 }),
	permission: mysqlEnum(['view','edit','comment']).default('view'),
	isPublic: tinyint("is_public").default(0),
	shareLink: varchar("share_link", { length: 255 }),
	expiresAt: timestamp("expires_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	accessedAt: timestamp("accessed_at", { mode: 'string' }),
},
(table) => [
	primaryKey({ columns: [table.id], name: "note_shares_id"}),
	unique("note_shares_share_link_unique").on(table.shareLink),
]);

export const noteTemplates = mysqlTable("note_templates", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	templateContent: text("template_content").notNull(),
	category: mysqlEnum(['general','subject_notes','exam_prep','revision','summary']).default('general'),
	subject: varchar({ length: 100 }),
	classLevel: varchar("class_level", { length: 20 }),
	isPublic: tinyint("is_public").default(0),
	createdByUserId: varchar("created_by_user_id", { length: 255 }),
	usageCount: int("usage_count").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "note_templates_id"}),
]);

export const notifications = mysqlTable("notifications", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	type: varchar({ length: 50 }),
	title: varchar({ length: 255 }),
	message: text(),
	isRead: tinyint("is_read").default(0),
	metadata: json(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "notifications_id"}),
]);

export const organization = mysqlTable("organization", {
	id: varchar({ length: 255 }).notNull(),
	name: text().notNull(),
	slug: varchar({ length: 255 }).notNull(),
	logo: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).notNull(),
	metadata: text(),
	subscriptionPlan: mysqlEnum("subscription_plan", ['starter','pro','enterprise']).default('starter'),
	subscriptionStatus: mysqlEnum("subscription_status", ['active','inactive','trial','pending','expired','cancelled']).default('trial'),
	settings: json(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "organization_id"}),
	unique("organization_slug_unique").on(table.slug),
]);

export const practestQuestionBank = mysqlTable("practest_question_bank", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	questionText: text("question_text"),
	questionType: text("question_type"),
	optionA: text("option_a"),
	optionB: text("option_b"),
	optionC: text("option_c"),
	optionD: text("option_d"),
	correctOption: text("correct_option"),
	modelAnswer: text("model_answer"),
	markingRubric: json("marking_rubric"),
	keywords: json(),
	explanation: text(),
	maxMarks: int("max_marks"),
	timeLimitSeconds: int("time_limit_seconds"),
	questionImageUrl: text("question_image_url"),
	optionImages: json("option_images"),
	explanationImageUrl: text("explanation_image_url"),
	hasMathContent: tinyint("has_math_content").default(0),
	hasChemicalFormulas: tinyint("has_chemical_formulas").default(0),
	hasDiagrams: tinyint("has_diagrams").default(0),
	board: text(),
	classLevel: int("class_level"),
	subject: text(),
	chapter: text(),
	topic: text(),
	subtopic: text(),
	usageCount: int("usage_count"),
	totalAttempts: int("total_attempts"),
	correctAttempts: int("correct_attempts"),
	averageTimeSeconds: int("average_time_seconds"),
	validationStatus: text("validation_status"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "practest_question_bank_id"}),
]);

export const practestTestConfigurations = mysqlTable("practest_test_configurations", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	name: text(),
	description: text(),
	board: text(),
	classLevel: int("class_level"),
	subject: text(),
	chapters: json(),
	topics: json(),
	totalQuestions: int("total_questions"),
	durationMinutes: int("duration_minutes"),
	maxMarks: int("max_marks"),
	negativeMarking: int("negative_marking"),
	partialMarking: tinyint("partial_marking").default(0),
	difficultyDistribution: json("difficulty_distribution"),
	questionTypeDistribution: json("question_type_distribution"),
	bloomDistribution: json("bloom_distribution"),
	randomizeQuestions: tinyint("randomize_questions").default(0),
	randomizeOptions: tinyint("randomize_options").default(0),
	allowReview: tinyint("allow_review").default(0),
	showResultsImmediately: tinyint("show_results_immediately").default(0),
	instructions: text(),
	rules: json(),
	isActive: tinyint("is_active").default(0),
	isPublic: tinyint("is_public").default(0),
	createdBy: text("created_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "practest_test_configurations_id"}),
]);

export const practestTestSessions = mysqlTable("practest_test_sessions", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }),
	configurationId: varchar("configuration_id", { length: 36 }).references(() => practestTestConfigurations.id, { onDelete: "cascade" } ),
	customParameters: json("custom_parameters"),
	selectedQuestions: json("selected_questions"),
	maxPossibleScore: int("max_possible_score"),
	startTime: timestamp("start_time", { mode: 'string' }),
	status: text(),
	currentQuestionIndex: int("current_question_index"),
	userResponses: json("user_responses"),
	timeRemainingSeconds: int("time_remaining_seconds"),
	totalScore: int("total_score"),
	percentage: int(),
	endTime: timestamp("end_time", { mode: 'string' }),
	durationSeconds: int("duration_seconds"),
	questionWiseResults: json("question_wise_results"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "practest_test_sessions_id"}),
]);

export const qdrantVectorIds = mysqlTable("qdrant_vector_ids", {
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	materialId: varchar("material_id", { length: 36 }).notNull().references(() => materials.id, { onDelete: "cascade" } ),
	pointId: varchar("point_id", { length: 36 }).notNull(),
	collection: varchar({ length: 100 }).notNull(),
	chunkIndex: int("chunk_index").notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
},
(table) => [
	index("idx_material_id").on(table.materialId),
	primaryKey({ columns: [table.id], name: "qdrant_vector_ids_id"}),
	unique("uq_collection_point").on(table.collection, table.pointId),
]);

export const quotaAlerts = mysqlTable("quota_alerts", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	alertType: varchar("alert_type", { length: 50 }),
	message: text(),
	isRead: tinyint("is_read").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "quota_alerts_id"}),
]);

export const sarvagyaCreditTransactions = mysqlTable("sarvagya_credit_transactions", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	amount: int().notNull(),
	type: varchar({ length: 50 }).notNull(),
	reason: text().notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "sarvagya_credit_transactions_id"}),
]);

export const sarvagyaDocuments = mysqlTable("sarvagya_documents", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	spaceId: varchar("space_id", { length: 36 }).references(() => sarvagyaSpaces.id),
	internalDocId: varchar("internal_doc_id", { length: 255 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	url: text(),
	fileType: varchar("file_type", { length: 50 }),
	size: int(),
	status: varchar({ length: 50 }),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "sarvagya_documents_id"}),
]);

export const sarvagyaQueries = mysqlTable("sarvagya_queries", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	spaceId: varchar("space_id", { length: 36 }).references(() => sarvagyaSpaces.id),
	userId: varchar("user_id", { length: 255 }).notNull(),
	query: text().notNull(),
	response: text(),
	tokensUsed: int("tokens_used").default(0),
	creditsDeducted: int("credits_deducted").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "sarvagya_queries_id"}),
]);

export const sarvagyaSpaces = mysqlTable("sarvagya_spaces", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	internalSpaceId: varchar("internal_space_id", { length: 255 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "sarvagya_spaces_id"}),
]);

export const session = mysqlTable("session", {
	id: varchar({ length: 255 }).notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	token: varchar({ length: 255 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow().notNull(),
	ipAddress: text("ip_address"),
	userAgent: text("user_agent"),
	userId: varchar("user_id", { length: 255 }).notNull().references(() => user.id, { onDelete: "cascade" } ),
	activeOrganizationId: varchar("active_organization_id", { length: 255 }),
},
(table) => [
	index("session_userId_idx").on(table.userId),
	primaryKey({ columns: [table.id], name: "session_id"}),
	unique("session_token_unique").on(table.token),
]);

export const subscriptionHistory = mysqlTable("subscription_history", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	subscriptionId: varchar("subscription_id", { length: 36 }).references(() => userSubscriptions.id),
	action: varchar({ length: 50 }),
	previousStatus: varchar("previous_status", { length: 50 }),
	newStatus: varchar("new_status", { length: 50 }),
	reason: text(),
	metadata: json(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "subscription_history_id"}),
]);

export const subscriptionPlans = mysqlTable("subscription_plans", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	planName: varchar("plan_name", { length: 100 }).notNull(),
	planCode: varchar("plan_code", { length: 50 }).notNull(),
	planType: mysqlEnum("plan_type", ['free_trial','board_access','class_access','subject_bundle','full_access']).notNull(),
	board: mysqlEnum(['CBSE','ICSE','STATE_BOARD','ALL','State']).notNull(),
	classLevel: int("class_level"),
	classAccessType: mysqlEnum("class_access_type", ['single','all']).default('single'),
	includedSubjects: json("included_subjects"),
	monthlyPrice: decimal("monthly_price", { precision: 10, scale: 2 }).default('0.00').notNull(),
	quarterlyPrice: decimal("quarterly_price", { precision: 10, scale: 2 }),
	yearlyPrice: decimal("yearly_price", { precision: 10, scale: 2 }),
	dailyQuestionLimit: int("daily_question_limit").default(30),
	features: json(),
	displayName: varchar("display_name", { length: 150 }).notNull(),
	description: text(),
	highlightText: varchar("highlight_text", { length: 255 }),
	displayOrder: int("display_order").default(0),
	isActive: tinyint("is_active").default(1),
	isFeatured: tinyint("is_featured").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "subscription_plans_id"}),
	unique("subscription_plans_plan_name_unique").on(table.planName),
	unique("subscription_plans_plan_code_unique").on(table.planCode),
]);

export const teacherActivityLogs = mysqlTable("teacher_activity_logs", {
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	teacherId: varchar("teacher_id", { length: 255 }).notNull().references(() => user.id, { onDelete: "cascade" } ),
	activityType: varchar("activity_type", { length: 100 }).notNull(),
	activityDescription: text("activity_description"),
	metadata: json(),
	ipAddress: varchar("ip_address", { length: 45 }),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "teacher_activity_logs_id"}),
]);

export const teacherClassAssignments = mysqlTable("teacher_class_assignments", {
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	teacherId: varchar("teacher_id", { length: 255 }).notNull().references(() => user.id, { onDelete: "cascade" } ),
	classId: varchar("class_id", { length: 36 }).notNull().references(() => classes.id, { onDelete: "cascade" } ),
	assignedBy: varchar("assigned_by", { length: 255 }),
	isActive: tinyint("is_active").default(1),
	assignedAt: timestamp("assigned_at", { mode: 'string' }).default(sql`(now())`),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "teacher_class_assignments_id"}),
]);

export const teacherVerificationDocuments = mysqlTable("teacher_verification_documents", {
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	teacherId: varchar("teacher_id", { length: 255 }).notNull().references(() => user.id, { onDelete: "cascade" } ),
	documentType: varchar("document_type", { length: 100 }).notNull(),
	filePath: text("file_path").notNull(),
	fileName: varchar("file_name", { length: 255 }).notNull(),
	fileSize: int("file_size"),
	mimeType: varchar("mime_type", { length: 100 }),
	status: varchar({ length: 50 }).default('pending').notNull(),
	notes: text(),
	reviewedBy: varchar("reviewed_by", { length: 255 }),
	reviewedAt: timestamp("reviewed_at", { mode: 'string' }),
	rejectionReason: text("rejection_reason"),
	uploadedAt: timestamp("uploaded_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "teacher_verification_documents_id"}),
]);

export const user = mysqlTable("user", {
	id: varchar({ length: 255 }).notNull(),
	name: text().notNull(),
	email: varchar({ length: 255 }).notNull(),
	emailVerified: tinyint("email_verified").default(0).notNull(),
	image: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow().notNull(),
	role: varchar({ length: 255 }).default('student'),
	classId: varchar("class_id", { length: 255 }),
	firstName: varchar("first_name", { length: 100 }),
	lastName: varchar("last_name", { length: 100 }),
	approvalStatus: mysqlEnum("approval_status", ['approved','pending','rejected']),
	verificationStatus: mysqlEnum("verification_status", ['verified_email','unverified','manual']),
	verificationMethod: varchar("verification_method", { length: 255 }),
	emailDomain: varchar("email_domain", { length: 255 }),
	isEducationalDomain: tinyint("is_educational_domain").default(0),
	verifiedAt: timestamp("verified_at", { mode: 'string' }),
	preferences: json(),
	lastLogin: timestamp("last_login", { mode: 'string' }),
	approvedBy: varchar("approved_by", { length: 255 }),
	approvedAt: timestamp("approved_at", { mode: 'string' }),
	rejectionReason: text("rejection_reason"),
},
(table) => [
	primaryKey({ columns: [table.id], name: "user_id"}),
	unique("user_email_unique").on(table.email),
]);

export const userMaterialAccess = mysqlTable("user_material_access", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }),
	accessType: text("access_type"),
	filterData: json("filter_data"),
	ipAddress: text("ip_address"),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
	materialId: varchar("material_id", { length: 36 }).references(() => materials.id, { onDelete: "cascade" } ),
	accessCount: int("access_count").default(1).notNull(),
},
(table) => [
	index("idx_uma_org_user").on(table.organizationId, table.userId),
	index("idx_uma_material").on(table.materialId),
	primaryKey({ columns: [table.id], name: "user_material_access_id"}),
	unique("uq_uma_user_material").on(table.userId, table.materialId),
]);

export const userNotes = mysqlTable("user_notes", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkId: varchar("clerk_id", { length: 255 }),
	title: varchar({ length: 500 }).notNull(),
	content: text().notNull(),
	subject: varchar({ length: 100 }),
	chapter: varchar({ length: 255 }),
	board: mysqlEnum(['CBSE','ICSE','STATE_BOARD']),
	classLevel: varchar("class_level", { length: 20 }),
	orientation: mysqlEnum(['portrait','landscape']).default('portrait'),
	tags: json(),
	sourceType: mysqlEnum("source_type", ['ai_tutor','manual','imported']).default('manual'),
	sourceQuery: text("source_query"),
	sourceAnswer: text("source_answer"),
	sourceVisualizations: json("source_visualizations"),
	folderId: varchar("folder_id", { length: 36 }),
	isFavorite: tinyint("is_favorite").default(0),
	isArchived: tinyint("is_archived").default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
	lastAccessedAt: timestamp("last_accessed_at", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "user_notes_id"}),
]);

export const userSubscriptions = mysqlTable("user_subscriptions", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: varchar({ length: 36 }).default(sql`(uuid())`).notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkId: varchar("clerk_id", { length: 255 }),
	subscriptionPlanId: varchar("subscription_plan_id", { length: 36 }).references(() => subscriptionPlans.id),
	subscriptionType: mysqlEnum("subscription_type", ['free_trial','board_access','class_access','subject_bundle','full_access']).notNull(),
	subscriptionStatus: mysqlEnum("subscription_status", ['active','inactive','trial','pending','expired','cancelled']).default('trial').notNull(),
	purchasedBoard: mysqlEnum("purchased_board", ['CBSE','ICSE','STATE_BOARD','ALL','State']),
	purchasedClass: int("purchased_class"),
	classAccessType: mysqlEnum("class_access_type", ['single','all']).default('single'),
	purchasedSubjects: json("purchased_subjects"),
	planName: varchar("plan_name", { length: 100 }).notNull(),
	planCode: varchar("plan_code", { length: 50 }).notNull(),
	monthlyPrice: decimal("monthly_price", { precision: 10, scale: 2 }).notNull(),
	billingCycle: mysqlEnum("billing_cycle", ['monthly','quarterly','yearly']).default('monthly'),
	dailyQuestionLimit: int("daily_question_limit").default(30),
	startDate: timestamp("start_date", { mode: 'string' }).default(sql`(now())`).notNull(),
	expiryDate: timestamp("expiry_date", { mode: 'string' }).notNull(),
	lastPaymentDate: timestamp("last_payment_date", { mode: 'string' }),
	nextBillingDate: timestamp("next_billing_date", { mode: 'string' }),
	cancelledAt: timestamp("cancelled_at", { mode: 'string' }),
	paymentStatus: mysqlEnum("payment_status", ['paid','pending','failed','refunded']).default('pending'),
	paymentGateway: varchar("payment_gateway", { length: 50 }),
	transactionId: varchar("transaction_id", { length: 255 }),
	paymentMetadata: json("payment_metadata"),
	autoRenew: tinyint("auto_renew").default(1),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
	sarvagyaCredits: int("sarvagya_credits").default(0),
	sarvagyaMonthlyQuota: int("sarvagya_monthly_quota").default(100),
	sarvagyaDailyLimit: int("sarvagya_daily_limit").default(10),
	lastCreditsReset: timestamp("last_credits_reset", { mode: 'string' }).default(sql`(now())`),
},
(table) => [
	primaryKey({ columns: [table.id], name: "user_subscriptions_id"}),
]);

export const userVocabProgress = mysqlTable("user_vocab_progress", {
	organizationId: varchar("organization_id", { length: 255 }).references(() => organization.id, { onDelete: "cascade" } ),
	id: serial().notNull(),
	userId: varchar("user_id", { length: 255 }).notNull(),
	clerkUserId: varchar("clerk_user_id", { length: 255 }),
	wordId: bigint("word_id", { mode: "number", unsigned: true }).notNull().references(() => dictionaryWords.id),
	efactor: decimal({ precision: 3, scale: 2 }).default('2.50'),
	intervalDays: int("interval_days").default(1),
	repetitions: int().default(0),
	// you can use { mode: 'date' }, if you want to have Date as type for this column
	nextDueDate: date("next_due_date", { mode: 'string' }).notNull(),
	lastReviewed: timestamp("last_reviewed", { mode: 'string' }),
	correctAttempts: int("correct_attempts").default(0),
	totalAttempts: int("total_attempts").default(0),
	accuracyPercentage: decimal("accuracy_percentage", { precision: 5, scale: 2 }).default('0.00'),
	status: mysqlEnum(['new','learning','review','mastered']).default('new'),
	firstLearnedAt: timestamp("first_learned_at", { mode: 'string' }),
	masteredAt: timestamp("mastered_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "user_vocab_progress_id"}),
	unique("id").on(table.id),
	unique("unique_user_word").on(table.userId, table.wordId),
]);

export const verification = mysqlTable("verification", {
	id: varchar({ length: 255 }).notNull(),
	identifier: varchar({ length: 255 }).notNull(),
	value: text().notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`(now())`).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`(now())`).onUpdateNow().notNull(),
},
(table) => [
	index("verification_identifier_idx").on(table.identifier),
	primaryKey({ columns: [table.id], name: "verification_id"}),
]);
