import crypto from 'crypto'

/**
 * Normalize a question string to handle variations in phrasing
 * 
 * Examples:
 * - "What is photosynthesis?" → "what is photosynthesis"
 * - "  Define photosynthesis  " → "define photosynthesis"
 * - "What is photosynthesis???" → "what is photosynthesis"
 * - "EXPLAIN PHOTOSYNTHESIS!" → "explain photosynthesis"
 */
function normalizeQuestion(question: string): string {
  return question
    .toLowerCase()                    // Convert to lowercase
    .replace(/[^\w\s]/g, '')          // Remove all punctuation
    .replace(/\s+/g, ' ')             // Replace multiple spaces with single space
    .trim()                           // Remove leading/trailing whitespace
}

/**
 * Generate a cache key for an AI answer
 * 
 * The cache key is generated by:
 * 1. Normalizing the question to handle variations in phrasing
 * 2. Including grade and subject if available
 * 3. Hashing the result with SHA256 for a compact key
 * 
 * @param question - The student's question
 * @param grade - Optional grade level (e.g., "10", "11", "12")
 * @param subject - Optional subject (e.g., "physics", "chemistry", "biology")
 * @returns A cache key string in format "answer:{hash}"
 * 
 * @example
 * ```typescript
 * // These all generate the same cache key:
 * generateCacheKey("What is photosynthesis?", "10", "biology")
 * generateCacheKey("what is photosynthesis", "10", "biology")
 * generateCacheKey("Define photosynthesis", "10", "biology")
 * 
 * // Different grade/subject = different cache key:
 * generateCacheKey("What is photosynthesis?", "11", "biology") // Different key
 * ```
 */
export function generateCacheKey(
  question: string,
  grade?: string,
  subject?: string
): string {
  // Normalize the question
  const normalizedQuestion = normalizeQuestion(question)
  
  // Build the cache key components
  const components = [normalizedQuestion]
  
  if (grade) {
    components.push(grade.toLowerCase().trim())
  }
  
  if (subject) {
    components.push(subject.toLowerCase().trim())
  }
  
  // Join components with a delimiter
  const cacheString = components.join(':')
  
  // Hash the string to create a compact cache key
  const hash = crypto
    .createHash('sha256')
    .update(cacheString)
    .digest('hex')
    .substring(0, 32) // Use first 32 characters for compactness
  
  return `answer:${hash}`
}

/**
 * Check if two questions would generate the same cache key
 * Useful for testing and debugging
 */
export function questionsMatch(
  question1: string,
  question2: string,
  grade?: string,
  subject?: string
): boolean {
  const key1 = generateCacheKey(question1, grade, subject)
  const key2 = generateCacheKey(question2, grade, subject)
  return key1 === key2
}

